"""Compile-time constants shared across the research package.

Extracting these from ResearchAgent keeps the class body lean and makes
the data accessible to module-level helpers without circular imports.
"""

import re

# ---------------------------------------------------------------------------
# Fallback source templates (used when search results are unavailable)
# ---------------------------------------------------------------------------
SOURCE_TEMPLATES: dict[str, str] = {
    "wikipedia": "https://en.wikipedia.org/wiki/{query}",
    "google_search": "https://www.google.com/search?q={query}",
    "google_news": "https://news.google.com/search?q={query}",
    "reddit": "https://www.reddit.com/search/?q={query}",
    "stackoverflow": "https://stackoverflow.com/search?q={query}",
    "github": "https://github.com/search?q={query}",
    "arxiv": "https://arxiv.org/search/?query={query}",
    "medium": "https://medium.com/search?q={query}",
    "devto": "https://dev.to/search?q={query}",
    "hackernews": "https://hn.algolia.com/?q={query}",
}

# ---------------------------------------------------------------------------
# Domain block/allow lists
# ---------------------------------------------------------------------------
BLACKLISTED_DOMAINS: frozenset[str] = frozenset(
    {
        "youtube.com",
        "www.youtube.com",
        "youtu.be",
        "instagram.com",
        "www.instagram.com",
        "tiktok.com",
        "www.tiktok.com",
        "vimeo.com",
        "facebook.com",
        "www.facebook.com",
    }
)

TRUSTED_DOMAINS: frozenset[str] = frozenset(
    {
        "wikipedia.org",
        "reuters.com",
        "apnews.com",
        "bloomberg.com",
        "nytimes.com",
        "wsj.com",
        "theguardian.com",
        "bbc.co.uk",
        "nature.com",
        "science.org",
        "arxiv.org",
        "scholar.google.com",
        "microsoft.com",
        "apple.com",
        "google.com",
        "github.com",
        "stackexchange.com",
        "stackoverflow.com",
        "nasa.gov",
        "nih.gov",
        "cdc.gov",
        "who.int",
        "un.org",
        "mit.edu",
        "stanford.edu",
        "harvard.edu",
        "ox.ac.uk",
        "cam.ac.uk",
        # Official language / framework documentation sites
        "docs.python.org",
        "docs.djangoproject.com",
        "fastapi.tiangolo.com",
        "flask.palletsprojects.com",
        "docs.sqlalchemy.org",
        "docs.pydantic.dev",
        "developer.mozilla.org",
        "reactjs.dev",
        "react.dev",
        "nextjs.org",
        "vuejs.org",
        "angular.io",
        "docs.npmjs.com",
        "nodejs.org",
        "typescriptlang.org",
        "www.typescriptlang.org",
        "bun.sh",
        "deno.land",
        "docs.docker.com",
        "kubernetes.io",
        "docs.aws.amazon.com",
        "cloud.google.com",
        "learn.microsoft.com",
        "docs.github.com",
        "platform.openai.com",
        "docs.anthropic.com",
        "ai.google.dev",
        "huggingface.co",
        "pytorch.org",
        "tensorflow.org",
        "rust-lang.org",
        "doc.rust-lang.org",
        "go.dev",
        "kotlinlang.org",
        "developer.apple.com",
        "docs.oracle.com",
        "pkg.go.dev",
        "docs.rs",
        "pypi.org",
        "rubygems.org",
        "packagist.org",
    }
)

# ---------------------------------------------------------------------------
# 5-tier source authority classification
# ---------------------------------------------------------------------------
SOURCE_TIERS: dict[int, frozenset] = {
    1: frozenset(
        {  # Official institutions & primary documents + official tech docs
            "nasa.gov",
            "nih.gov",
            "cdc.gov",
            "fda.gov",
            "epa.gov",
            "sec.gov",
            "whitehouse.gov",
            "congress.gov",
            "ec.europa.eu",
            "who.int",
            "un.org",
            "worldbank.org",
            "imf.org",
            "oecd.org",
            "europa.eu",
            "bbc.co.uk",
            "iaea.org",
            # Official language & framework documentation
            "docs.python.org",
            "docs.djangoproject.com",
            "fastapi.tiangolo.com",
            "flask.palletsprojects.com",
            "docs.sqlalchemy.org",
            "docs.pydantic.dev",
            "developer.mozilla.org",
            "reactjs.dev",
            "react.dev",
            "nextjs.org",
            "vuejs.org",
            "angular.io",
            "docs.npmjs.com",
            "nodejs.org",
            "typescriptlang.org",
            "www.typescriptlang.org",
            "bun.sh",
            "deno.land",
            "docs.docker.com",
            "kubernetes.io",
            "docs.aws.amazon.com",
            "cloud.google.com",
            "learn.microsoft.com",
            "docs.github.com",
            "platform.openai.com",
            "docs.anthropic.com",
            "ai.google.dev",
            "huggingface.co",
            "pytorch.org",
            "tensorflow.org",
            "rust-lang.org",
            "doc.rust-lang.org",
            "go.dev",
            "kotlinlang.org",
            "developer.apple.com",
            "docs.oracle.com",
            "pkg.go.dev",
            "docs.rs",
            "pypi.org",
        }
    ),
    2: frozenset(
        {  # Academic research
            "arxiv.org",
            "scholar.google.com",
            "nature.com",
            "science.org",
            "pubmed.ncbi.nlm.nih.gov",
            "ncbi.nlm.nih.gov",
            "jstor.org",
            "ssrn.com",
            "biorxiv.org",
            "medrxiv.org",
            "mit.edu",
            "stanford.edu",
            "harvard.edu",
            "ox.ac.uk",
            "cam.ac.uk",
        }
    ),
    3: frozenset(
        {  # Established major media
            "reuters.com",
            "apnews.com",
            "bloomberg.com",
            "nytimes.com",
            "wsj.com",
            "theguardian.com",
            "bbc.com",
            "ft.com",
            "economist.com",
            "washingtonpost.com",
            "time.com",
            "theatlantic.com",
            "nbcnews.com",
            "cbsnews.com",
            "cnn.com",
            "edition.cnn.com",
            "abcnews.go.com",
            "aljazeera.com",
            "pbs.org",
            "npr.org",
            "independent.co.uk",
            "newsweek.com",
            "foxnews.com",
            "politico.com",
            "axios.com",
            "cnbc.com",
            "thehill.com",
        }
    ),
    4: frozenset(
        {  # Recognized research orgs & reference
            "wikipedia.org",
            "rand.org",
            "brookings.edu",
            "pewresearch.org",
            "ourworldindata.org",
            "statista.com",
            "github.com",
            "stackoverflow.com",
            "stackexchange.com",
            "microsoft.com",
            "google.com",
            "apple.com",
            "understandingwar.org",
            "timesofisrael.com",
            "haaretz.com",
            "foreignpolicy.com",
            "cfr.org",
            "chathamhouse.org",
            "sipri.org",
        }
    ),
}

# ---------------------------------------------------------------------------
# Date extraction patterns
# ---------------------------------------------------------------------------
DATE_PATTERNS: tuple = (
    # JSON metadata fields: "datePublished":"2024-03-15"
    re.compile(r'"(?:datePublished|date|publishedAt|pubDate)"\s*:\s*"(\d{4}-\d{2}-\d{2})'),
    # Standalone ISO 8601 date in text
    re.compile(r"\b(202[0-9]-(?:0[1-9]|1[0-2])-(?:0[1-9]|[12]\d|3[01]))\b"),
    # Written US date: March 15, 2024
    re.compile(
        r"\b(?:January|February|March|April|May|June|July|August|September"
        r"|October|November|December)\s+\d{1,2},?\s+(202[0-9])\b"
    ),
)

# ---------------------------------------------------------------------------
# Internationalized status messages
# ---------------------------------------------------------------------------
STATUS_MESSAGES: dict[str, dict[str, str]] = {
    "tr": {
        "starting_research": "Araştırma başlatılıyor: {query}",
        "preparing_queries": "Arama sorguları hazırlanıyor...",
        "planning_strategy": "Araştırma stratejisi planlanıyor...",
        "search_ready_query": "Arama sorgusu: {query}",
        "search_variants": "Arama sorgusu varyantları: {count}",
        "research_plan": "Araştırma Planı:",
        "sources_to_check": "Kontrol edilecek kaynak: {count}",
        "source_types": "Kaynak türleri: {types}",
        "research_depth_label": "Araştırma derinliği: {depth}",
        "gathering_data": "Kaynaklardan veri toplanıyor...",
        "source_failed": "{source}: Başarısız - {error}",
        "source_success": "{source}: {title}... ({chars} karakter)",
        "results_summary": "Sonuçlar: {successful}/{total} kaynak başarılı",
        "total_content": "Toplanan içerik: {chars} karakter",
        "synthesizing": "Bulgular analiz ediliyor ve sentezleniyor...",
        "generated_variants": "Daha iyi sonuçlar için {count} arama sorgusu varyantı oluşturuldu.",
        "found_sources": "{count} potansiyel kaynak bulundu. Derinlik: {depth}",
        "gathered_chars": "{successful}/{total} kaynaktan {chars} karakter toplandı.",
        "research_failed": "Araştırma başarısız oldu: {error}",
        "analyzing_complexity": "Sorgu karmaşıklığı analiz ediliyor ve eş zamanlı aranıyor...",
        "searching_sources": "En fazla {count} yüksek kaliteli kaynak aranıyor...",
        "ranking_results": "En iyi {count} sonuç sıralanıp seçiliyor...",
        "analyzing_deep": "Derin araştırma için sorgu karmaşıklığı analiz ediliyor...",
    },
    "en": {
        "starting_research": "Starting research on: {query}",
        "preparing_queries": "Preparing search-ready queries...",
        "planning_strategy": "Planning research strategy...",
        "search_ready_query": "Search-ready query: {query}",
        "search_variants": "Search query variants: {count}",
        "research_plan": "Research Plan:",
        "sources_to_check": "Sources to check: {count}",
        "source_types": "Source types: {types}",
        "research_depth_label": "Research depth: {depth}",
        "gathering_data": "Gathering data from sources...",
        "source_failed": "{source}: Failed - {error}",
        "source_success": "{source}: {title}... ({chars} chars)",
        "results_summary": "Results: {successful}/{total} sources successful",
        "total_content": "Total content gathered: {chars} characters",
        "synthesizing": "Analyzing and synthesizing findings...",
        "generated_variants": "Generated {count} search query variants for better retrieval.",
        "found_sources": "Found {count} potential sources to check. Depth: {depth}",
        "gathered_chars": "Gathered {chars} characters from {successful}/{total} sources.",
        "research_failed": "Research failed: {error}",
        "analyzing_complexity": "Analyzing query complexity and searching concurrently...",
        "searching_sources": "Searching for up to {count} high-quality sources...",
        "ranking_results": "Ranking and selecting top {count} results...",
        "analyzing_deep": "Analyzing query complexity for deep research...",
    },
}

# ---------------------------------------------------------------------------
# Technology → official documentation URL mapping
# ---------------------------------------------------------------------------
TECH_DOC_URLS: dict[str, list[str]] = {
    "python": ["https://docs.python.org/3/", "https://pypi.org/"],
    "django": ["https://docs.djangoproject.com/en/stable/"],
    "fastapi": ["https://fastapi.tiangolo.com/"],
    "flask": ["https://flask.palletsprojects.com/"],
    "sqlalchemy": ["https://docs.sqlalchemy.org/en/latest/"],
    "pydantic": ["https://docs.pydantic.dev/latest/"],
    "javascript": ["https://developer.mozilla.org/en-US/docs/Web/JavaScript"],
    "typescript": ["https://www.typescriptlang.org/docs/"],
    "react": ["https://react.dev/reference/react"],
    "nextjs": ["https://nextjs.org/docs"],
    "next.js": ["https://nextjs.org/docs"],
    "vue": ["https://vuejs.org/guide/"],
    "angular": ["https://angular.io/docs"],
    "nodejs": ["https://nodejs.org/en/docs/"],
    "node.js": ["https://nodejs.org/en/docs/"],
    "docker": ["https://docs.docker.com/"],
    "kubernetes": ["https://kubernetes.io/docs/"],
    "openai": ["https://platform.openai.com/docs/"],
    "anthropic": ["https://docs.anthropic.com/"],
    "claude": ["https://docs.anthropic.com/"],
    "rust": ["https://doc.rust-lang.org/book/"],
    "golang": ["https://go.dev/doc/"],
    "go": ["https://go.dev/doc/"],
    "kotlin": ["https://kotlinlang.org/docs/"],
    "swift": ["https://developer.apple.com/documentation/swift"],
    "pytorch": ["https://pytorch.org/docs/stable/"],
    "tensorflow": ["https://www.tensorflow.org/api_docs"],
    "huggingface": ["https://huggingface.co/docs"],
    "aws": ["https://docs.aws.amazon.com/"],
    "azure": ["https://learn.microsoft.com/en-us/azure/"],
    "gcp": ["https://cloud.google.com/docs"],
    "terraform": ["https://developer.hashicorp.com/terraform/docs"],
    "ansible": ["https://docs.ansible.com/"],
    "html": ["https://developer.mozilla.org/en-US/docs/Web/HTML"],
    "css": ["https://developer.mozilla.org/en-US/docs/Web/CSS"],
    "sql": ["https://www.w3schools.com/sql/", "https://dev.mysql.com/doc/"],
    "postgresql": ["https://www.postgresql.org/docs/current/"],
    "mysql": ["https://dev.mysql.com/doc/"],
    "mongodb": ["https://www.mongodb.com/docs/"],
    "redis": ["https://redis.io/docs/"],
}
